name: Docker
on:
  push:
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
 
 # Run tests for any PRs.
  pull_request:

env:
  IMAGE_NAME: aceproxy

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run:  
          echo "Test"
          #docker build . --file Dockerfile
        
  push:
    # Ensure test job passes before pushing image.
    #needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: build-push
      - uses: actions/checkout@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/aceproxy
          tags: latest
