name: Docker
on:
  push:
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

env:
  IMAGE_NAME: aceproxy
  VERSION: latest

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: docker build . --file Dockerfile --tag image
        
  push:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
        - uses: actions/checkout@v2
        - name: build
          run: docker build . --file Dockerfile --tag $IMAGE_NAME
        - name: Log into registry
          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
        - name: Push image
          run: |
            docker tag image docker.pkg.github.com/dank100/docker-acestream-proxy/$IMAGE_NAME:$VERSION
            docker push docker.pkg.github.com/dank100/docker-acestream-proxy/$IMAGE_NAME:$VERSION
