name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image and push
      with:
        image: dank100/docker-acestream-proxy:$(date +%s)
        tage: latest
        registry: docker.pkg.github.com
        dockerfile: Dockerfile
        username: dank100
        password: ${{ secrets.DOCKER_PASSWORD }}
